"""Reproducible, authored lesson packs. No model/API calls at build or run time."""
import json,hashlib
from pathlib import Path
ROOT=Path('public/data')
def save(id,summary,ideas,terms,mastery,reflection,rows):
 source=json.loads((ROOT/'lectures'/f'{id}.json').read_text())
 assert len(source['transcript'])>1000
 questions=[]
 for i,(q,right,wrong,why) in enumerate(rows):
  answer=[2,0,3,1,1,3,0,2,3,1,2,0][i];options=list(wrong);options.insert(answer,right)
  questions.append(dict(question=q,options=options,answer=answer,explanation=why))
 data=dict(basis='transcript',summary=summary,keyIdeas=[dict(title=t,explanation=e) for t,e in ideas],terms=[dict(term=t,definition=d) for t,d in terms],mastery=[dict(question=q,answer=a) for q,a in mastery],reflection=reflection,quiz=questions,readings=[],sourceUrl=source['sourceUrl'],sourceHash=hashlib.sha256(source['transcript'].encode()).hexdigest(),sourceNote='Prepared from the complete published lecture transcript. Interpretive positions are attributed to the lecturer; these questions are independent study aids, not Yale assessments. Source: '+source['sourceUrl'],preparedBy='AI-assisted editorial preparation',status='published')
 (ROOT/'guides'/f'{id}.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))

save('c9-l1',
'''Christine Hayes introduces the Hebrew Bible as a diverse anthology produced, edited, and transmitted by ancient communities. Her course combines historical, literary, and cultural inquiry rather than treating the collection as a single author’s systematic theology. Its human history is the object of investigation; questions of divine inspiration are not adjudicated by the course.

Hayes places Israel within the ancient Near East. Biblical narratives share material with neighboring traditions, but their adaptations can express distinctive claims about divine power, human responsibility, and justice. Her comparison of flood traditions illustrates why differences in a shared story matter as much as similarities. She also distinguishes the convictions of final editors from the older traditions they incorporated.

Several reading habits must change. Biblical figures are morally complex, and a narrative’s inclusion of an action does not automatically endorse it. Different biblical voices can remain in tension. The reader must attend to genre, artistry, and the historical circumstances of each work.

Finally, Hayes maps the collection: Torah, Prophets, and Writings constitute the Tanakh. Greek translation, different community canons, and manuscript transmission complicate the idea of a single unchanging Bible. Her preference for “Hebrew Bible” keeps the academic object of study distinct from the theological implications of “Old Testament.” The central task is careful reading before harmonization or doctrinal synthesis.''',
[('An anthology with many voices','Different genres and historical settings yield diverse perspectives. Hayes asks readers to preserve these differences rather than assume that every biblical voice says the same thing.'),('Shared stories, changed meanings','The flood comparison shows how similar narrative elements can support different accounts of divine motivation and human wrongdoing.'),('Editors and inherited traditions','A final editorial perspective need not perfectly erase earlier voices. Tensions can illuminate the history of a text’s composition.'),('Characters are not automatic moral models','Hayes emphasizes psychologically complex figures capable of deception, failure, growth, and loyalty. Portrayal must be distinguished from endorsement.'),('Community and canon','The Tanakh’s three divisions and the Septuagint’s different arrangement show that communities organize and authorize collections in different ways.'),('An academic method with limits','The course investigates the demonstrably human production and transmission of the texts. It does not require either affirming or denying divine inspiration.')],
[('Tanakh','An acronym for Torah, Nevi’im, and Ketuvim.'),('Torah','Instruction or teaching; the first five books of the Hebrew Bible.'),('Nevi’im','Prophets: narrative Former Prophets and prophetic writings.'),('Ketuvim','Writings: the third, varied division of the Tanakh.'),('Septuagint','Ancient Greek translation tradition of Jewish scriptures.')],
[('Why does the library metaphor change how one reads the Bible?','A library contains works with different purposes, genres, and settings. Apparent disagreement can be significant evidence rather than an error to harmonize immediately.'),('What can the comparison of flood stories establish?','It reveals a shared narrative world and distinctive transformations of that world. Hayes stresses differing divine motivations rather than equating every version’s message.'),('How could an older tradition resist the perspective of a later editor?','An editor can retain inherited language or narrative features whose implications sit uneasily beside the final work’s dominant theology.'),('Why might defending every action of a biblical protagonist weaken interpretation?','It can erase the moral conflict and character development through which a narrative explores human experience.'),('Distinguish canon from textual transmission.','Canon concerns which works a community treats as authoritative; textual transmission concerns the copying and preservation of those works, including variants.'),('How does Hayes distinguish academic inquiry from an argument against faith?','She brackets claims about inspiration while examining human authorship, editing, and reception. Those methodological limits do not settle the theological question.')],
['Choose a morally ambiguous biblical scene. What changes when you ask what the narrative exposes rather than immediately defend its protagonist?','Which tensions between biblical voices have you been taught to harmonize? What might become visible if you first describe the differences accurately?','How does the name “Old Testament,” “Hebrew Bible,” or “Tanakh” shape the expectations you bring to the same texts?','Compare the motivations for the flood discussed in the lecture. How do competing portraits of divine power affect your understanding of responsibility and justice?'],
[
('Why does Hayes describe the Bible as a library?','It collects diverse works composed and edited in different settings',['Its books all share one literary genre','Its present order follows one author’s outline','It was first written as a library catalogue'],'The metaphor highlights diversity of genre, setting, and voice, which a single-book model can obscure.'),
('What does Hayes emphasize when comparing biblical and Mesopotamian flood narratives?','Similar plots can carry different theological and ethical meanings',['Similarity proves that their messages are identical','Only differences in the number of animals matter','A shared plot makes historical context irrelevant'],'She draws attention to the transformation of inherited narrative material, particularly the explanation of why the flood occurs.'),
('A biblical protagonist deceives someone. Which reading practice best follows Hayes’s introduction?','Examine how the narrative portrays the act and its consequences',['Assume the action must be a model because the person is biblical','Remove the passage from consideration','Treat the character as psychologically incapable of change'],'Hayes warns against converting complex literary characters into flawless exemplars.'),
('What is the academic course’s stance toward divine inspiration?','It leaves that faith question aside while studying human textual processes',['It claims archaeology can prove inspiration','It makes denial of inspiration a course requirement','It assumes inspiration eliminates editorial history'],'The method focuses on what can be investigated historically and literarily without deciding the theological issue.'),
('What does the acronym Tanakh name?','Torah, Prophets, and Writings',['Torah, Psalms, and Gospels','Law, Epistles, and Apocalypse','Patriarchs, Kings, and Apostles'],'The three Hebrew names are Torah, Nevi’im, and Ketuvim.'),
('Why does Hayes prefer “instruction” to a narrow translation of Torah as “law”?','It better conveys the scope of teaching implied by the term',['It excludes all legal material','It means the collection has no narratives','It identifies a Greek rather than Hebrew word'],'Instruction includes more than a modern reader may imagine when hearing only the word law.'),
('What does comparing biblical canons ask first?','Which works different communities regard as authoritative',['Which surviving manuscript has the largest handwriting','Whether every book uses the same poetic meter','How many chapters a modern publisher prints per page'],'Canonical boundaries concern the recognized collection; manuscript and layout questions are different issues.'),
('What is the Septuagint in this lecture?','A Greek translation tradition important to Jewish and Christian readers',['A medieval Latin commentary on the Gospels','A collection written only in Aramaic','The name of the final division of the Tanakh'],'Hayes uses the Septuagint to show how translation and arrangement affected the reception of scripture.'),
('Why are the Dead Sea Scrolls important to Hayes’s discussion?','They substantially extend the available early manuscript evidence',['They provide the original autograph of every biblical book','They eliminate all textual variants','They demonstrate that the Bible was originally written in Latin'],'Earlier witnesses illuminate both continuity and variation; they do not supply every original manuscript.'),
('How should a reader initially handle dissonant biblical perspectives?','Describe each voice carefully before seeking a synthesis',['Assume one must be a copying mistake','Assign every passage an identical setting','Replace all difficult passages with later doctrinal formulas'],'Hayes treats the preservation of diverse voices as something to investigate and appreciate.'),
('What distinguishes a narrative from a catechism in Hayes’s discussion?','Narrative can explore moral and existential questions indirectly',['Narrative cannot address religious concerns','A catechism necessarily predates every narrative','Narrative always states a single explicit moral after each scene'],'Story, metaphor, and character can address questions without the form of systematic propositions.'),
('What might a tension between older material and a final editorial perspective indicate?','A layered history of composition and interpretation',['That the passage has no interpretable meaning','That no editor ever worked on the collection','That all biblical books were written at one moment'],'The final collection may retain traces of inherited traditions alongside later editorial commitments.')])

save('c4-l1',
'''Dale Martin begins by asking why a university class should study the New Testament and what kind of study it will undertake. He distinguishes reading a document as a community’s scripture from examining it as historical evidence. The course prioritizes the meanings of early Christian writings in their ancient settings rather than devotional application or the entire history of their later influence.

An opening exercise separates statements in the texts from familiar later traditions. Its larger purpose is methodological: cultural familiarity can create confidence without close textual knowledge. Martin asks religious and nonreligious students alike to suspend inherited assumptions long enough to notice what the documents actually contain.

A rapid tour exposes literary diversity. Four Gospels retell related material differently; Acts resembles ancient travel narratives in some respects; letters address particular communities and problems; Hebrews raises questions about its conventional title; Revelation presents visionary and apocalyptic imagery. Genre, audience, performance, and historical context therefore matter.

Martin then imagines an outsider encountering an early Christian gathering. He translates familiar religious vocabulary into less familiar everyday language to expose how insiders and outsiders might hear it differently. The imaginary account includes misunderstandings and rumors, not a literal description of every Christian practice. The course will recover diverse early Christian positions on Jesus, Jewish law, women, slavery, and imperial power before considering later efforts at unity.''',
[('Scripture within a community','Martin treats scriptural status as a relationship between a text and a community that receives it as sacred. The classroom’s historical question is different from a church’s devotional question.'),('Tradition is not identical with textual wording','Familiar images and doctrines may belong to later interpretation. Close reading distinguishes a document’s statements from the cultural memory surrounding it.'),('Twenty-seven documents, multiple genres','Gospels, letters, narrative, homiletic discourse, and apocalypse require attention to distinct forms and purposes.'),('Ancient audiences and public reading','Martin asks what a letter would do when read aloud in a gathered community, rather than assuming modern private reading conditions.'),('Vocabulary can conceal strangeness','Ordinary meanings behind familiar terms help expose the distance between modern expectations and ancient usage.'),('Diversity before synthesis','The course separates voices and contexts to investigate early Christian disagreements before imposing later unity.')],
[('Historical-critical study','Inquiry into a text’s historical circumstances, literary character, and early meanings.'),('Reception','The ways later readers and communities interpret and use a text.'),('Genre','A recognizable literary form that shapes interpretation.'),('Apocalypse','Revelation or disclosure; a label associated with visionary literature.'),('Exegesis','Careful interpretation of a particular passage in its literary and historical setting.')],
[('How do devotional and historical readings ask different questions?','A devotional reading may seek an authoritative word for a believing community; historical inquiry asks how documents functioned in particular ancient contexts.'),('Why can a nonreligious student also bring preconceptions?','Cultural exposure to Christianity supplies assumptions even without church participation. Martin asks all students to examine that inherited familiarity.'),('What is the point of distinguishing three gifts from three visitors?','It illustrates how a remembered tradition can exceed the wording of the narrative. The first task is identifying what the text actually says.'),('Why does public reading matter for interpreting a letter?','Tone, exhortation, social conflict, and group identity may function differently in a gathered community from how they appear to an isolated modern reader.'),('What must one avoid when using Martin’s imagined outsider scene?','Do not treat hostile rumors or deliberate misunderstandings as straightforward evidence that Christians practiced everything the outsider suspects.'),('How does investigating diversity change the course’s method?','It invites comparison among particular documents and communities rather than assuming a single theology, practice, or social position across all early Christians.')],
['Which “biblical” idea in your inherited imagination might actually come from art, liturgy, or later tradition? How would you check?','Try describing one familiar religious practice in ordinary language. What does that clarify, and what does it distort?','How might hearing a Pauline letter with an entire community change the questions you ask about it?','What would it mean to describe an early Christian disagreement fairly before deciding which position you favor?'],
[
('What is Martin’s principal aim for this course?','To investigate early Christian documents in their historical contexts',['To prescribe one church’s devotional interpretation','To survey all Western art inspired by scripture','To assume later Christian doctrines resolve every textual difference'],'He distinguishes his historical focus from both confessional reading and a comprehensive reception history.'),
('In Martin’s framing, what makes a document scripture for a group?','The community receives it as sacred and authoritative',['Its parchment has a special chemical composition','Its literary genre must be poetry','Every person who encounters it must recognize it as holy'],'He emphasizes a relationship of reception, rather than treating sacred status as a universally self-evident property.'),
('Why does the opening exercise distinguish the visitors to Jesus from their gifts?','To expose an assumption supplied by later tradition rather than explicit wording',['To show Matthew contains no visitors at all','To establish that the gifts are not mentioned','To prove all later traditions are historically worthless'],'The example teaches precise textual observation without requiring dismissal of the cultural importance of tradition.'),
('What does Martin ask of students who grew up without religion?','To examine cultural assumptions they may still bring to the text',['To assume they have no prior conceptions','To adopt a denomination before attending','To avoid interpreting religious vocabulary'],'Participation in a culture influenced by Christianity can create familiarity even outside religious households.'),
('Why discuss genre during the introductory tour?','Different literary forms create different interpretive expectations',['Every New Testament document is a private diary','Genre determines whether a text is morally good','Genre makes historical context unnecessary'],'Letters, narratives, and visions do different kinds of work for their audiences.'),
('What question does Martin raise about reading early Christian letters?','How they would be heard when read aloud in a community',['Whether they were primarily written for solitary modern readers','Why they contain no social concerns','Whether their recipients all lived in one city'],'Communal performance is part of the historical setting, not merely a modern delivery preference.'),
('What is the role of the imagined outsider in Corinth?','To make familiar Christian language appear unfamiliar and potentially misunderstood',['To provide a verbatim diary from a known seamstress','To establish that every rumor about Christians was true','To replace textual evidence with fiction'],'The thought experiment defamiliarizes vocabulary. Its suspicions are not presented as reliable reports of all Christian behavior.'),
('Which distinction best captures Martin’s treatment of the Trinity in the opening exercise?','Later doctrinal formulation is distinguishable from its use of New Testament material',['No later theologian ever used the New Testament','All first-century Christians used the later creed’s exact wording','Historical study can by itself settle the doctrine’s theological truth'],'He separates the history of doctrinal formulation from the theological judgment that later readers may make about it.'),
('Why compare the four Gospels rather than immediately combine them?','Their different presentations are evidence for distinct perspectives',['Only the longest Gospel can be interpreted','Differences make all four historically meaningless','Their titles guarantee identical authorship'],'Comparison attends to the diversity that a harmonized narrative can obscure.'),
('Which question concerns reception history rather than the course’s primary early-context focus?','How later paintings portray Peter’s death',['What social problem an early letter addresses','What an ancient audience might understand by a term','What genre a first-century narrative uses'],'Reception history asks how later communities use and interpret earlier texts.'),
('What does Martin’s emphasis on early Christianities invite students to investigate?','Differences in belief, practice, identity, and social relationships',['A movement with no meaningful disagreements','Only the eventual majority position','A single unchanged institution from the beginning'],'The plural framing directs attention to historical diversity and the processes that later sought unity.'),
('Which approach best applies the lecture to a familiar passage?','Identify its genre, setting, and audience, then distinguish its wording from later assumptions',['Begin by combining every later interpretation into the text','Treat familiarity as sufficient evidence of understanding','Ignore translation because all versions express identical choices'],'This combines close reading with historical context while making inherited assumptions available for examination.')])

save('c61-l1',
'''Paul Freedman introduces early medieval history through the Roman Empire’s durability, its crises, and the surprising survival of its institutions and memories. Christianity, the Byzantine Empire, emerging kingdoms, and Islam will each participate in the transformation of the Roman world. The course therefore asks both what ended and what continued.

Freedman uses Edward Gibbon’s admiration for the second-century empire as a point of comparison, not as an unquestioned verdict. Security and stability were significant achievements, but their benefits were unequal. Imperial laws protected property, political power had practical limits, and tolerance depended on accepting Roman expectations of civilized life. Christianity exposed a conspicuous limit to religious tolerance.

The Mediterranean formed the empire’s geographic and cultural center. A shared elite culture, local civic patronage, cities, and familiar institutions helped connect an enormous territory. Force alone could not maintain that coherence. Yet urban-rural tensions, an increasingly prosperous East relative to the West, and problems of scale put pressure on the system.

The third-century army’s ability to make and unmake emperors brought succession instability into focus. Diocletian’s later intervention will show that this first crisis could be survived, while the fifth-century West faced a different outcome. Freedman resists a single predetermined explanation: external enemies, internal weaknesses, religious change, and regional continuity must be weighed together.''',
[('An empire with several heirs','The course follows Roman legacies through the Western church, Byzantium, successor kingdoms, and the regions transformed by Islam.'),('Gibbon is an interpreter','His praise of the second century and criticism of Christianity reflect an Enlightenment perspective that the lecture interrogates.'),('Stability is not equal benefit','Durability and security are compatible with social inequality and laws that privilege property holders.'),('The Mediterranean as center','Control of the sea’s shores and a shared cultural orientation made the Mediterranean fundamental to Roman organization.'),('Civic elites connect the system','Local benefactors and common elite practices sustained urban institutions and contributed to imperial cohesion.'),('Crisis requires explanation','Long-standing weaknesses alone do not explain why crises occur at a particular time or why regions experience different outcomes.')],
[('Late antiquity','A period used to study transformations linking the ancient and early medieval worlds.'),('Byzantine Empire','Modern name for the Eastern Roman Empire, which maintained a Roman political identity.'),('Civic patronage','Local elites’ support of public activities and institutions.'),('Succession','The process by which one ruler is replaced by another.'),('Continuity and change','A historical distinction between persisting forms and transformations.')],
[('Why does the survival of the East complicate “the fall of Rome”?','It prevents the Western imperial collapse from standing for the disappearance of every Roman political institution or identity.'),('How does Freedman qualify Gibbon’s praise of the empire?','He asks who benefited from its security and laws, and highlights the position of groups omitted from an elite-centered account.'),('Why could the army not hold the empire together by itself?','Local elites, shared practices, and civic institutions performed work of integration that military force alone could not supply.'),('How can tolerance coexist with exclusion?','Rome permitted many forms of worship but drew boundaries around accepted behavior and identity, including limits affecting Christians.'),('What distinguishes a structural weakness from a sufficient explanation of collapse?','A weakness can persist during stability. An explanation must also account for timing, mechanisms, and different regional outcomes.'),('What question should frame the study of Christianity and empire?','How religious change transformed political and cultural life, rather than assuming in advance that Christianity single-handedly caused collapse.')],
['Whose experience disappears when an empire is called peaceful or prosperous? Apply Freedman’s critique of Gibbon to a modern historical narrative.','How can a community preserve institutions belonging to a power that once persecuted it? Consider the lecture’s church–empire paradox.','Where do you see the difference between impressive claims of authority and an institution’s actual capacity to act?','What evidence would help distinguish transformation from catastrophe in the Roman world? Would every social group answer alike?'],
[
('Why does Freedman discuss Byzantine survival?','It complicates treating Western collapse as the end of the entire Roman world',['It shows the eastern empire had no Roman identity','It proves that no political change occurred anywhere','It removes the need to study the fifth century'],'Roman institutions and identity continued in the East, so periodization must distinguish regions.'),
('How does the lecture use Gibbon’s favorable image of the second century?','As an influential interpretation to evaluate critically',['As a neutral description shared by every ancient resident','As proof that the empire provided equal rights','As a contemporary report written by a Roman emperor'],'Freedman respects the importance of Gibbon’s narrative while challenging its assumptions and exclusions.'),
('Which question most directly challenges an elite-centered account of Roman happiness?','How did slaves, peasants, and women experience imperial order?',['How many modern editions of Gibbon exist?','Did all Roman buildings use the same stone?','What was the longest emperor’s name?'],'Asking who benefited broadens evaluation beyond the security of propertied elites.'),
('What made the Mediterranean central to Roman power?','The empire controlled its shores and oriented much of its life around it',['It separated all provinces from imperial contact','Roman elites universally preferred inland frontiers','It was outside Rome’s political jurisdiction'],'The sea was a unifying political, logistical, and cultural center.'),
('What role did local elites play?','They supported civic institutions and shared practices that helped integrate the empire',['They eliminated the need for any army','They refused all public expenditure','They lived entirely outside cities'],'Local patronage and a common elite culture supplemented state and military power.'),
('Why does Freedman qualify Roman tolerance?','It permitted much diversity while imposing boundaries and persecuting Christians at times',['It meant every belief and practice was equally protected','It excluded every non-Roman deity','It was a modern system of universal individual rights'],'The lecture treats tolerance as historically significant but conditional.'),
('Which third-century development destabilized imperial rule?','Armies repeatedly made and unmade emperors',['A peaceful succession rule became universally accepted','The empire permanently abolished its army','Every province became an independent democracy'],'Military intervention in succession produced short and often violent reigns.'),
('Which regional imbalance does Freedman identify?','The East had become more prosperous and commercially developed than the West',['The East contained no cities','The West alone participated in Mediterranean trade','Both regions had identical economic conditions'],'This asymmetry helps frame later divergent trajectories.'),
('Why is pointing to long-standing flaws insufficient to explain a crisis?','It does not yet explain why the system fails at that particular time',['Structural features can never matter historically','Every empire has exactly the same weaknesses','Only a single ruler’s personality counts'],'A causal account needs mechanisms and timing as well as a list of vulnerabilities.'),
('What paradox concerns Christianity and Roman inheritance?','A once-persecuted movement became a major preserver of Roman legacies',['Christianity began as Rome’s only legal religion','The Western church rejected every use of Latin','Religious institutions cannot preserve political cultures'],'Freedman uses this reversal to introduce the complicated afterlife of empire.'),
('Which comparison is central to the course’s treatment of crisis?','The third-century recovery and the later Western collapse',['The Roman and modern Olympic medal counts','The length of every emperor’s speeches','The number of churches in modern capitals'],'The empire’s survival of one crisis makes later failure something requiring explanation.'),
('Which historical approach best follows the lecture?','Weigh internal weakness, external pressure, religious change, and regional continuity',['Assume Christianity alone explains every outcome','Treat all provinces as experiencing identical change','Read later collapse as inevitable from the beginning'],'Freedman presents debated causal questions and warns against a simple predetermined story.')])

save('c61-l2',
'''Freedman examines the third-century crisis as a combination of foreign pressure, unstable succession, and economic strain. Sassanid Persia threatened the eastern frontier, while attacks across the Rhine and Danube challenged the northern boundaries. Military leaders rose and fell rapidly, and rewards paid to soldiers could encourage repeated changes of emperor. Nevertheless, political turmoil did not affect every person or institution in exactly the same way.

Inflation and debased coinage spread economic disruption. Increasing military expenditure strained the government, while the weakening of local elites damaged institutions that had helped sustain civic life. Freedman also connects their decline to changes in the social environment of religious practice.

Diocletian sought restoration through radical reorganization. A larger army required more effective collection of resources; inventories of land and population supported taxation, and requisitions supplied soldiers directly. The tetrarchy distributed imperial responsibility among two senior and two junior rulers. Imperial presentation became more distant, ceremonial, and sacred.

The results were mixed. The succession arrangement failed to endure, price controls encouraged evasion and black markets, and persecution did not suppress Christianity. Yet improved defense and administration helped the empire recover. Freedman distinguishes the failure of particular policies from the achievement of imperial survival, and asks readers not to mistake hindsight about later collapse for the experience of contemporaries who felt that order had returned.''',
[('Several pressures converge','Frontier invasions, unstable succession, and fiscal strain reinforced one another; no single item exhausts the crisis.'),('Military incentives matter','Donatives rewarded troops when a new emperor appeared, creating an incentive structure that could undermine stable rule.'),('Coinage and confidence','Debasement reduced precious-metal content, encouraged the circulation of poorer coins, and contributed to inflation and uncertainty.'),('Taxation supports defense','Diocletian’s administrative work sought a more effective valuation and collection of resources to support an expanded army.'),('Rule is reorganized','The tetrarchy divided duties among two Augusti and two Caesars, while court ceremony elevated the distance and authority of the emperor.'),('Mixed outcomes, substantial survival','Price controls and the succession system failed, but the state’s recovery makes it misleading to call the whole reform program unsuccessful.')],
[('Donative','A payment to soldiers associated with an emperor’s accession.'),('Debasement','Reducing a coin’s precious-metal content while attempting to preserve its stated value.'),('Tetrarchy','Rule by four: two senior Augusti and two junior Caesars.'),('Requisition','Obtaining goods directly for state purposes, including military supply.'),('Edict on Prices','Diocletian’s attempt to control prices by legal limits.')],
[('How could rewarding soldiers destabilize succession?','A payment associated with each new ruler could make another change of ruler materially attractive to the army.'),('Why distinguish political instability from ordinary experience?','Institutions and daily activities may continue through turmoil at the top. The effects of crisis must be demonstrated rather than assumed uniform.'),('How does debasement differ from borrowing?','Debasement changes coin content; borrowing anticipates future revenue through debt. Freedman uses the absence of modern-style debt financing to frame Roman fiscal constraints.'),('Why did tax reform require administrative information?','Assessors needed knowledge of land, population, and productive capacity to estimate obligations and reduce evasion.'),('Why might the tetrarchy help administration but fail as a succession system?','Dividing responsibilities addresses scale and distance, but rival ambitions and dynastic expectations can still disrupt agreed transfers of power.'),('How should Diocletian’s overall achievement be assessed?','Separate individual policy failures from improved military and fiscal capacity, and distinguish contemporary recovery from later Western collapse.')],
['How can an institution create incentives that undermine its stated purpose? Compare the lecture’s donatives with a system you know.','When does a reform preserve an institution by substantially changing it? Use Diocletian’s conservative goals and radical methods as your example.','What does the contrast between political turmoil and continuing ordinary life teach you about whose evidence to seek?','How does knowing an institution’s later fate distort your account of an earlier recovery? What would a contemporary observer have seen?'],
[
('Which combination describes the immediate pressures in the third-century crisis?','Foreign invasions and unstable imperial succession',['Universal peace and a settled succession law','The disappearance of all provincial armies','A complete cessation of taxation throughout the empire'],'Freedman places invasions and succession at the center of the immediate crisis, alongside structural vulnerabilities.'),
('What was a donative?','A payment to soldiers linked to an emperor’s accession',['A tax exemption for every farmer','A title given to a junior emperor','A religious ban on coinage'],'Repeated accession payments could encourage troops to support repeated changes of ruler.'),
('Why does the lecture distinguish political turmoil from daily life?','Some institutions and activities continued despite instability at the top',['Political events never affect anyone','All provinces experienced identical collapse','Only emperors can leave historical evidence'],'The degree of social disruption must be investigated rather than inferred directly from a list of short reigns.'),
('What is coinage debasement?','Reducing precious-metal content while retaining a claimed face value',['Increasing metal content without changing value','Replacing every coin with a government bond','Prohibiting all exchange of goods'],'The lecture connects this fiscal expedient with inflation and uncertainty about value.'),
('In the lecture’s explanation, why might poorer coins remain in circulation?','People spend them while retaining better coins',['Every coin’s metal content is identical','The government forbids anyone to hold valuable objects','Better coins cannot be stored'],'Freedman uses the tendency to hoard better money to explain how poorer currency can dominate exchange.'),
('Why was information about land and population important to Diocletian?','It supported more systematic assessment and collection of taxes',['It replaced the need for an army','It established modern income-tax payroll records','It guaranteed equal wealth across the empire'],'Productive resources had to be assessed in an economy where wealth was not primarily represented by modern salaries.'),
('What was the tetrarchy’s basic structure?','Two senior emperors and two junior colleagues',['One emperor and three elected assemblies','Four unrelated independent republics','Two emperors without designated assistants'],'The Augusti and Caesars distributed responsibility, though cooperation and succession remained problematic.'),
('Which distinction best describes Diocletian’s reforming stance?','Conservative goals pursued through radical changes',['Revolutionary goals pursued without administrative change','An intention to abolish imperial government','A refusal to address frontier defense'],'He sought to preserve imperial order by significantly reorganizing its machinery.'),
('Why did the Edict on Prices struggle?','Fixed legal prices encouraged evasion and black markets',['It abolished all demand for goods','It permanently ended scarcity in every province','It applied only to imaginary commodities'],'Freedman explains how legal prices and actual market pressures could diverge.'),
('How did the emperor’s public image change?','It became more distant, ceremonial, and exalted',['It became exclusively an informal local office','All court ceremony was prohibited','The emperor was presented as having no special authority'],'The lecture connects administrative reorganization with a more sacred and remote presentation of rulership.'),
('Which policy failure should not erase Diocletian’s broader achievement?','The breakdown of the tetrarchic succession system',['A permanent inability to defend any frontier','The immediate extinction of the entire empire','The complete disappearance of imperial administration'],'A failed succession arrangement coexisted with meaningful recovery in defense and state capacity.'),
('How does Freedman caution against hindsight?','Later Western collapse should not erase the reality of fourth-century recovery',['Contemporaries all knew precisely when the West would fall','Historians must ignore every later event','Every reform inevitably failed within a year'],'Contemporaries could experience restored order even when historians know that later crises would follow.')])
print('Prepared four transcript-grounded static lesson packs.')
