import json
from pathlib import Path
r=Path('public/data');a=json.loads((r/'transcript-audit.json').read_text());s=json.loads((r/'content-status.json').read_text());c=s['coverage']
lines=['# Transcript acquisition status','', 'Updated 2026-09-27. Counts describe acquired text, not verification against audio. Formatting cleanup preserves the lecturer’s wording. Publisher texts without republication permission remain linked rather than mirrored in the app.','',f"{c['acquiredTranscripts']} transcripts acquired and format-cleaned; {c['studyPacks']} static study packs; {c['questions']} multiple-choice questions.",'', '## Access and matching barriers','', '- BiblicalTraining: direct retrieval encountered a Cloudflare verification challenge. Its copyright terms restrict reposting; authorized transcript exports can support preparation while the app links to the originals.', '- YouTube: automated caption access encountered a verification challenge. Caption files or authorized downloadable audio would enable further preparation; alternate original-publisher sources are still being investigated.', '- Reasonable Faith: only pages embedding the exact catalog video ID are matched. Similar titles and matching part numbers alone are insufficient.', '- Five catalog courses still lack a verified lecture list. Their missing lectures are not included in the numerical backlog.', '', '## Course coverage','', '| Course | Listed lectures | Text acquired | Study packs |','|---|---:|---:|---:|']
for x in a['courses']:
 n=s['courseCoverage'][x['courseId']]['studyPacks'];lines.append(f"| {x['title']} | {x['lectures']} | {x['acquired']} | {n} |")
lines+=['','The complete per-lesson audit is in `public/data/transcript-audit.json`. A missing transcript is marked not-yet-acquired rather than presumed nonexistent.','', '## Resuming preparation','', '1. Acquire full text from the original publisher and verify the lecture match.', '2. Run `python scripts/clean-transcripts.py` and inspect the cleaned text. Formatting cleanup is not a claim of audio verification.', '3. Prepare a static guide from the complete transcript. Include summary, outline, mastery answers, reflection prompts, and explained multiple-choice questions.', '4. Run `python scripts/build-transcript-audit.py`, `node scripts/validate-content.mjs`, and `npm run build` before publication.','']
Path('TRANSCRIPTS.md').write_text('\n'.join(lines))
p=Path('README.md');t=p.read_text();start=t.index('62 courses /');end=t.index('\n\nYale transcripts',start);t=t[:start]+f"62 courses / {c['lessons']:,} listed full lectures, with {c['supplementalVideos']} supplemental previews kept separately. {c['acquiredTranscripts']} transcripts acquired and format-cleaned: {c['inlineTranscripts']} available inline and {c['publisherTranscripts']} linked to publishers. {c['publisherStudyGuides']} publisher study-guide links and {c['studyPacks']} static study packs with {c['questions']} multiple-choice questions. Missing content is marked with an icon and pack count on course cards, study paths, and course headers. See TRANSCRIPTS.md for the acquisition audit and ROADMAP.md for remaining work."+t[end:];p.write_text(t)
p=Path('ROADMAP.md');t=p.read_text().replace('42 static','44 static').replace('650 quiz','682 quiz').replace('42 lectures','44 lectures').replace('1,644 remain','1,642 remain');t=t.replace('167 publisher transcript links',str(c['publisherTranscripts'])+' publisher transcript links').replace('167 more link',str(c['publisherTranscripts'])+' more link').replace('1,447 have no',f"{c['lessons']-c['acquiredTranscripts']:,} have no");t+='\nDetailed transcript acquisition and access barriers: [TRANSCRIPTS.md](TRANSCRIPTS.md).\n' if 'Detailed transcript acquisition' not in t else '';p.write_text(t)
