import React,{useState,useEffect,useMemo} from 'react';
import{createRoot}from'react-dom/client';
import{BookOpen,Map,Library,Flame,Gem,Target,Check,Play,ArrowRight,ArrowLeft,ChevronRight,ChevronDown,Star,Trophy,Heart,Search,NotebookPen,Settings,Volume2,Clock,ExternalLink,Download,Upload,RefreshCw,X,CheckCircle2,HelpCircle,Lightbulb,GraduationCap,ScrollText,Sparkles,Link,ShieldCheck,Copy,CalendarDays,Menu,RotateCcw}from'lucide-react';
import './style.css';
const icons={learn:Map,courses:Library,practice:Target,notebook:NotebookPen,progress:Trophy};
const labels={learn:'Learn',courses:'Courses',practice:'Practice',notebook:'Notebook',progress:'Your journey'};
const empty=()=>({version:1,active:'Dalmo',selected:'c31',goal:3,people:{Dalmo:{done:{},quiz:{},notes:{},days:{}},Viv:{done:{},quiz:{},notes:{},days:{}}}});
function load(){try{const s=JSON.parse(localStorage.getItem('bibledegree-v1'));return s?.version===1&&s.people?.Dalmo&&s.people?.Viv?s:empty()}catch{return empty()}}
function day(){return new Date().toLocaleDateString('en-CA')}
function ext(url){return /^https?:\/\//.test(url||'')?url:'#'}
function App(){
 const[catalog,setCatalog]=useState([]),[state,setState]=useState(load),[route,setRoute]=useState(location.hash.slice(1)||'/learn'),[error,setError]=useState(''),[toast,setToast]=useState(''),[settings,setSettings]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[showAll,setShowAll]=useState(false);
 useEffect(()=>{fetch('/data/catalog.json').then(r=>{if(!r.ok)throw Error('Cannot load courses');return r.json()}).then(setCatalog).catch(e=>setError(e.message))},[]);
 useEffect(()=>{const h=()=>{setRoute(location.hash.slice(1)||'/learn');window.scrollTo(0,0)};window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h)},[]);
 useEffect(()=>{try{localStorage.setItem('bibledegree-v1',JSON.stringify(state))}catch{setError('Your browser could not save progress. Export a backup in Settings.')}},[state]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t)}},[toast]);
 const p=state.people[state.active],other=state.people[state.active==='Dalmo'?'Viv':'Dalmo'];
 function update(fn){setState(s=>{const n=structuredClone(s);fn(n,n.people[n.active]);return n})}
 function notify(t){setToast(t)}
 const course=catalog.find(c=>c.id===state.selected)||catalog.find(c=>c.id==='c31');
 const completed=(c,person=p)=>c.completed||!!person.done['course:'+c.id]||(c.lessons.length>0&&c.lessons.every(l=>person.done[l.id]));
 const count=(c,person=p)=>completed(c,person)?c.lessons.length:c.lessons.filter(l=>person.done[l.id]).length;
 const totalDone=catalog.filter(c=>completed(c)).length;
 const xp=Object.keys(p.done).filter(k=>!k.startsWith('course:')).length*20+Object.values(p.quiz).reduce((a,q)=>a+(q.best||0)*5,0);
 const streak=(()=>{let n=0,d=new Date();if(!p.days[day()])d.setDate(d.getDate()-1);while(p.days[d.toLocaleDateString('en-CA')]){n++;d.setDate(d.getDate()-1)}return n})();
 const lessonId=route.startsWith('/lesson/')?route.split('/')[2].split('?')[0]:null;
 const lessonCourse=lessonId?catalog.find(c=>c.lessons.some(l=>l.id===lessonId)):null;
 const lesson=lessonCourse?.lessons.find(l=>l.id===lessonId);
 function selectCourse(c){update(n=>n.selected=c.id);setShowAll(false);location.hash='/learn'}
 function mark(l,done=true){update((n,u)=>{if(done){u.done[l.id]=new Date().toISOString();u.days[day()]=true}else delete u.done[l.id]});notify(done?'Lesson complete. Keep growing!':'Lesson marked incomplete')}
 function saveNote(id,v){update((n,u)=>u.notes[id]={text:v,updated:new Date().toISOString()})}
 function recordQuiz(id,correct,total,mistakes){update((n,u)=>{const prev=u.quiz[id];u.quiz[id]={best:Math.max(prev?.best||0,correct),total,attempts:(prev?.attempts||0)+1,last:correct,mistakes,updated:new Date().toISOString()};u.days[day()]=true});}
 const next=course?.lessons.find(l=>!p.done[l.id])||course?.lessons[0];
 const weekDone=Object.keys(p.done).filter(k=>!k.startsWith('course:')&&new Date(p.done[k])>new Date(Date.now()-7*86400000)).length;
 if(error&&!catalog.length)return <div className="loading"><BookOpen size={50}/><h1>Let’s reconnect.</h1><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></div>;
 if(!course)return <div className="loading"><BookOpen className="breathe" size={52}/><h2>Opening your books…</h2></div>;
 return <><aside className="sidebar"><a href="#/learn" className="brand"><BookOpen size={35} strokeWidth={3}/><span>bible<span>degree</span></span></a><nav>{Object.entries(labels).map(([k,v])=>{const Icon=icons[k];return <a key={k} href={'#/'+k} className={route==='/'+k?'active':''}><Icon/><span>{v}</span></a>})}</nav><div className="sidebar-bottom"><div className="together-mark"><Heart size={21}/><span>Dalmo & Viv<br/><small>Learning, together.</small></span></div><button className="plain" onClick={()=>setSettings(true)}><Settings size={21}/> Settings & backup</button></div></aside>
 <div className="shell"><header className="topbar"><a href="#/learn" className="mobile-brand"><BookOpen/> bibledegree</a><span className="top-context">YOUR FREE THEOLOGICAL EDUCATION</span><div className="top-stats"><span title="Study day streak" className="streak"><Flame fill="currentColor" size={23}/>{streak}</span><span title="Practice experience" className="xp"><Gem fill="#c4eef3" size={23}/>{xp}<small>XP</small></span><button className="avatar" aria-label="Switch learner" onClick={()=>update(n=>n.active=n.active==='Dalmo'?'Viv':'Dalmo')}>{state.active==='Dalmo'?'D':'V'}</button></div></header>
 <div className={'body-grid '+(lesson?'lecture-grid':'')}><main id="main">
 {route==='/learn'&&<><div className="page-heading"><div><p className="eyebrow">ONE STEP AT A TIME</p><h1>Your learning path</h1></div><button className="text-button" onClick={()=>location.hash='/courses'}>Change course <ChevronDown size={18}/></button></div><section className="course-banner"><div><span>{course.section.toUpperCase()} · NEXT CHAPTER</span><h2>{course.title}</h2><p>{course.professor}</p></div><div className="banner-icon"><ScrollText size={48} strokeWidth={1.7}/></div><div className="banner-progress"><div className="track"><i style={{width:100*count(course)/(course.lessons.length||1)+'%'}}/></div><small>{count(course)} / {course.lessons.length} lessons</small></div></section>
 {course.note&&<p className="source-note">{course.note}</p>}
 <div className="path-intro"><span>{completed(course)?'READY FOR A REFRESH?':'YOUR NEXT LESSON'}</span><p>{next?.title||'Open the course to begin'}</p></div>
 {course.lessons.length?<div className="learning-path">{course.lessons.slice(0,showAll?undefined:8).map((l,i)=>{const done=completed(course)||p.done[l.id],active=l.id===next?.id;return <React.Fragment key={l.id}>{i>0&&i%6===0&&<div className="unit-divider"><span>CHAPTER {Math.floor(i/6)+1}</span><strong>Keep the story going</strong></div>}<div className={'path-stop '+(active?'current':'')+' '+(done?'finished':'')} style={{'--offset':`${[0,64,98,64,0,-64,-98,-64][i%8]}px`}}>{active&&<span className="start-callout">{done?'REVISIT':'START HERE'}</span>}<a className="lesson-node" href={'#/lesson/'+l.id} aria-label={'Lesson '+(i+1)+': '+l.title}>{done?<Check size={34} strokeWidth={4}/>:active?<Play size={31} fill="currentColor"/>:<BookOpen size={29}/>}</a><div className="path-label"><span>LESSON {i+1}{l.duration?' · '+l.duration:''}</span><strong>{l.title}</strong></div>{i===2&&<img src="/lamb.webp" className="path-lamb" alt="A cheerful lamb reading a book"/>}</div></React.Fragment>})}</div>:<div className="empty-state"><Library size={42}/><h2>Continue at the course provider</h2><p>{course.sourceIssue||'This older course link does not currently expose a verified lecture list.'}</p><a className="button primary" href={ext(course.url)} target="_blank" rel="noreferrer">Open course <ExternalLink size={18}/></a></div>}
 {!showAll&&course.lessons.length>8&&<button className="button outline more-lessons" onClick={()=>setShowAll(true)}>Show all {course.lessons.length} lessons <ChevronDown size={18}/></button>}
 <div className="course-footer"><a href={ext(course.url)} target="_blank" rel="noreferrer">Original course <ExternalLink size={15}/></a><button className="text-button" onClick={()=>{update((n,u)=>{if(u.done['course:'+course.id])delete u.done['course:'+course.id];else u.done['course:'+course.id]=new Date().toISOString()});notify('Course progress updated')}}>{p.done['course:'+course.id]?'Undo course completion':'Mark course completed'}</button></div></>}
 {route==='/courses'&&<><div className="page-heading"><div><p className="eyebrow">A LIFETIME OF LEARNING</p><h1>Your course library</h1><p>{catalog.length} courses · {catalog.reduce((s,c)=>s+c.hours,0).toLocaleString()} cataloged hours</p></div></div><label className="search-box"><Search size={22}/><input placeholder="Find a course, professor, or subject" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="filter-row">{['All','Biblical Studies','Theology & History','Philosophy, Ethics, etc.','Electives'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='Philosophy, Ethics, etc.'?'Philosophy & ethics':f}</button>)}</div><div className="course-list">{catalog.filter(c=>(filter==='All'||c.section===filter)&&`${c.title} ${c.professor} ${c.area}`.toLowerCase().includes(search.toLowerCase())).map((c,i)=><button key={c.id} className="course-card" onClick={()=>selectCourse(c)}><div className={'course-emblem tone-'+i%4}>{completed(c)?<Check size={31}/>:<BookOpen size={31}/>}</div><div><small>{c.area}</small><h3>{c.title}</h3><p>{c.professor}</p><span>{c.lessons.length?`${c.lessons.length} lessons · `:''}{c.hours} hours{completed(c)?' · Completed':''}</span></div><ChevronRight size={22}/></button>)}</div>{!catalog.some(c=>(filter==='All'||c.section===filter)&&`${c.title} ${c.professor} ${c.area}`.toLowerCase().includes(search.toLowerCase()))&&<p className="empty-state">No courses match. Try another title or professor.</p>}<p className="fineprint">Imported from your curriculum. Hours reflect the sheet’s estimates. Alternatives are separate courses, not separate degree requirements. Independent study does not confer an accredited MDiv.</p></>}
 {lesson&&<Lesson key={lesson.id+state.active} lesson={lesson} course={lessonCourse} person={p} profile={state.active} mark={mark} saveNote={saveNote} recordQuiz={recordQuiz} notify={notify} update={update}/>}
 {lessonId&&!lesson&&<div className="empty-state"><h1>Lesson not found</h1><a className="button primary" href="#/courses">Browse courses</a></div>}
 {route==='/practice'&&<><div className="page-heading"><div><p className="eyebrow">MAKE IT STICK</p><h1>Practice with purpose</h1></div></div><div className="practice-hero"><Target size={65}/><div><h2>Understanding grows with practice.</h2><p>Revisit a lesson, retrieve what you remember, and strengthen the ideas that need another look.</p></div></div><h2 className="section-heading">Your review queue</h2>{Object.entries(p.quiz).length?Object.entries(p.quiz).map(([id,q])=>{const c=catalog.find(c=>c.lessons.some(l=>l.id===id)),l=c?.lessons.find(l=>l.id===id);return l&&<a className="review-card" key={id} href={'#/lesson/'+id+'?tab=quiz'}><div><h3>{l.title}</h3><p>{q.mistakes?.length?`${q.mistakes.length} questions to revisit`:'Ready for a fresh review'} · {q.attempts} attempts</p></div><strong>{Math.round(q.best/q.total*100)}%</strong><ChevronRight/></a>}):<div className="empty-state"><Lightbulb size={42}/><h3>Your first quiz starts here.</h3><p>Take the quiz inside a lecture. Missed questions will appear in your review queue.</p><a className="button primary" href={'#/lesson/'+next?.id+'?tab=quiz'}>Practice the next lesson <ArrowRight size={18}/></a></div>}</>}
 {route==='/notebook'&&<><div className="page-heading"><div><p className="eyebrow">THINK IT THROUGH</p><h1>{state.active}’s notebook</h1></div></div><p className="muted">Your reflections, questions, and connections.</p>{Object.entries(p.notes).filter(([,n])=>n.text?.trim()).length?Object.entries(p.notes).filter(([,n])=>n.text?.trim()).sort((a,b)=>b[1].updated.localeCompare(a[1].updated)).map(([id,n])=>{const c=catalog.find(c=>c.lessons.some(l=>l.id===id)),l=c?.lessons.find(l=>l.id===id);return <article className="note-card" key={id}><small>{c?.title}</small><h2><a href={'#/lesson/'+id+'?tab=reflect'}>{l?.title||id}</a></h2><p>{n.text}</p><span>Saved {new Date(n.updated).toLocaleDateString()}</span></article>}):<div className="empty-state"><NotebookPen size={45}/><h2>Leave room for wonder.</h2><p>Your notes from each lecture will gather here.</p><a href={'#/lesson/'+next?.id+'?tab=reflect'} className="button primary">Write your first reflection</a></div>}</>}
 {route==='/progress'&&<><div className="page-heading"><div><p className="eyebrow">LOOK HOW FAR YOU’VE COME</p><h1>Your journey, together</h1></div></div><div className="journey-hero"><img src="/lamb.webp" alt="Reading lamb"/><div><h2>{totalDone} courses completed</h2><p>One shared pursuit. Two growing perspectives.</p><span className="gold-text">{xp} XP earned through practice</span></div></div><div className="couple-grid">{['Dalmo','Viv'].map(name=>{const u=state.people[name];return <section className="panel" key={name}><span className={'avatar '+(name==='Viv'?'viv':'')}>{name[0]}</span><h2>{name}</h2><p>{catalog.filter(c=>completed(c,u)).length} courses completed</p><p>{Object.keys(u.quiz).length} lectures practiced</p><p>{Object.values(u.notes).filter(n=>n.text?.trim()).length} reflections</p></section>})}</div><h2 className="section-heading">Your foundations</h2>{catalog.filter(c=>completed(c)).map(c=><div className="achievement" key={c.id}><div><GraduationCap size={33}/></div><span><h3>{c.title}</h3><p>{c.professor}</p><small>{c.completed?'Completed together · Summer 2026':'Course completed'}</small></span><CheckCircle2/></div>)}<h2 className="section-heading">Across the curriculum</h2>{['Biblical Studies','Theology & History','Philosophy, Ethics, etc.','Electives'].map(s=>{const list=catalog.filter(c=>c.section===s),n=list.filter(c=>completed(c)).length;return <div className="subject-progress" key={s}><div><strong>{s}</strong><span>{n} / {list.length}</span></div><div className="track"><i style={{width:100*n/list.length+'%'}}/></div></div>})}</>}
 </main>{!lesson&&<aside className="right-rail"><div className="learner-switch"><button className={state.active==='Dalmo'?'selected':''} onClick={()=>update(n=>n.active='Dalmo')}>Dalmo</button><button className={state.active==='Viv'?'selected':''} onClick={()=>update(n=>n.active='Viv')}>Viv</button></div><section className="panel weekly"><div className="panel-heading"><h3>This week’s goal</h3><Target className="teal"/></div><p><strong>{Math.min(weekDone,state.goal)}</strong> / {state.goal} lessons</p><div className="track gold"><i style={{width:Math.min(100,weekDone/state.goal*100)+'%'}}/></div><div className="week-days">{Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);return <span className={p.days[d.toLocaleDateString('en-CA')]?'studied':''} key={i}><small>{['M','T','W','T','F','S','S'][i]}</small><i>{p.days[d.toLocaleDateString('en-CA')]?<Check size={13}/>:''}</i></span>})}</div></section><section className="panel together"><div className="panel-heading"><h3>Better together</h3><Heart className="coral" size={22}/></div><div className="pair-avatars"><span>D</span><span>V</span></div><p>You’ve already completed<br/><strong>two Yale courses together.</strong></p><a href="#/progress" className="text-button">See your journey <ArrowRight size={16}/></a></section><section className="encouragement"><img src="/lamb.webp" alt="Your scholarly lamb companion"/><div><h3>A little curiosity.<br/>A little every day.</h3><p>There’s a whole world<br/>behind the next lesson.</p></div></section><footer className="rail-footer"><a href="https://docs.google.com/spreadsheets/d/1UJOSlaq4o7OGXxcGCIqzivz5BX3-UDwy4JiuA9_3nZM/edit" target="_blank" rel="noreferrer">Your curriculum ↗</a><span>Independent study · No tuition</span></footer></aside>}</div></div>
 <nav className="mobile-nav">{Object.entries(labels).map(([k,v])=>{const Icon=icons[k];return <a href={'#/'+k} key={k} className={route==='/'+k?'active':''}><Icon/><span>{k==='progress'?'Journey':v}</span></a>})}<button aria-label="Settings" onClick={()=>setSettings(true)}><Settings/></button></nav>
 {toast&&<div role="status" className="toast"><CheckCircle2 size={20}/>{toast}</div>}{error&&<div role="alert" className="toast error">{error}</div>}{settings&&<SettingsModal state={state} setState={setState} close={()=>setSettings(false)} notify={notify}/>}
 </>;
}
function Lesson({lesson:l,course:c,person,profile,mark,saveNote,recordQuiz,notify}){
 const initial=location.hash.split('?tab=')[1]||'watch';const[tab,setTab]=useState(initial),[source,setSource]=useState(null),[guide,setGuide]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[note,setNote]=useState(person.notes[l.id]?.text||''),[transcriptSearch,setTranscriptSearch]=useState(''),[paste,setPaste]=useState(''),[showPaste,setShowPaste]=useState(false),[quizActive,setQuizActive]=useState(false);
 const i=c.lessons.findIndex(x=>x.id===l.id),next=c.lessons[i+1];
 useEffect(()=>{let live=true;fetch('/data/lectures/'+l.id+'.json').then(r=>r.ok?r.json():null).then(s=>{if(live)setSource(s)}).catch(()=>{});fetch('/data/guides/'+l.id+'.json').then(async r=>{if(r.ok&&r.headers.get('content-type')?.includes('json'))return r.json();const cached=await fetch('/api/study?lessonId='+l.id);return cached.ok&&cached.headers.get('content-type')?.includes('json')?cached.json():null}).then(g=>{if(live&&g)setGuide(g)}).catch(()=>{});return()=>{live=false}},[l.id]);
 useEffect(()=>{const t=setTimeout(()=>{if(note!==(person.notes[l.id]?.text||''))saveNote(l.id,note)},600);return()=>clearTimeout(t)},[note]);
 const allReadings=[...(source?.readings||l.readings||[]),...(c.readings||[]),...(guide?.readings||[])];
 async function generate(){setBusy(true);setErr('');try{const r=await fetch('/api/study',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonId:l.id,transcript:paste||undefined})});const data=await r.json();if(!r.ok)throw Error(data.error||'Study guide is temporarily unavailable.');setGuide(data);setShowPaste(false)}catch(e){setErr(e.message)}finally{setBusy(false)}}
 const guideTools=<div className="guide-loader"><Sparkles size={32}/><h3>{busy?'Preparing your study companion…':'Build your study companion'}</h3><p>{busy?'Finding the main ideas, meaningful questions, and useful connections.':source?.transcript?'Create a summary, mastery questions, reflections, and a 12-question quiz from the lecture transcript.':'Create a topic guide and practice questions. Without a verified transcript, it will be labeled as supplementary study rather than a lecture summary.'}</p><button className="button primary" onClick={generate} disabled={busy}>{busy?<RefreshCw className="spin" size={18}/>:<Sparkles size={18}/>} {busy?'Preparing…':'Prepare study guide'}</button><button className="text-button" onClick={()=>setShowPaste(!showPaste)}>Use a transcript you have</button>{showPaste&&<textarea aria-label="Paste lecture transcript" placeholder="Paste the lecture transcript here…" value={paste} onChange={e=>setPaste(e.target.value)} maxLength={90000}/>}<small>AI study aids can make mistakes. Compare them with the lecture and primary texts.</small>{err&&<p role="alert" className="error-text">{err}</p>}</div>;
 return <><a className="back-link" href="#/learn"><ArrowLeft size={19}/> Back to your path</a><div className="lecture-heading"><p className="eyebrow">{c.title} · LESSON {i+1} OF {c.lessons.length}</p><h1>{l.title}</h1><p>{c.professor}{l.duration&&<> <span>·</span> {l.duration}</>}</p></div><div className="lesson-tabs" role="tablist">{[['watch',Play,'Watch'],['summary',Sparkles,'Summary'],['mastery',Lightbulb,'Mastery'],['reflect',NotebookPen,'Reflect'],['quiz',Target,'Quiz'],['read',BookOpen,'Readings'],['transcript',ScrollText,'Transcript']].map(([k,Icon,label])=><button key={k} role="tab" aria-selected={tab===k} className={tab===k?'selected':''} onClick={()=>{setTab(k);setQuizActive(false)}}><Icon size={18}/>{label}</button>)}</div>
 <div className="lesson-content" role="tabpanel">
 {tab==='watch'&&<><div className="video-wrap">{l.videoId?<iframe title={l.title} src={'https://www.youtube-nocookie.com/embed/'+l.videoId} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>:<div className="audio-placeholder"><Volume2 size={54}/><h2>Listen with the course provider</h2><p>This lecture is hosted as audio or on an external player.</p><a className="button primary" href={ext(l.url||c.url)} target="_blank" rel="noreferrer">Open lecture <ExternalLink size={18}/></a></div>}</div><div className="under-video"><span><Clock size={17}/>{l.duration||'Study at your own pace'}</span><a href={ext(l.url)} target="_blank" rel="noreferrer">{l.sourceKind==='course'?'Course provider':'Original lecture'} <ExternalLink size={16}/></a></div>{(source?.overview||l.overview)&&<section className="lecture-overview"><h2>In this lecture</h2><p>{source?.overview||l.overview}</p><small>Course provider’s overview · <a href={ext(l.url)} target="_blank" rel="noreferrer">Source</a></small></section>}<div className="next-action"><div><h3>Watch. Wonder. Make it yours.</h3><p>Then test your understanding and reflect together.</p></div><button className="button primary" onClick={()=>setTab('summary')}>Study this lesson <ArrowRight size={18}/></button></div></>}
 {tab==='summary'&&(guide?<><div className="ai-label"><Sparkles size={17}/>{guide.basis==='transcript'?'AI summary · based on lecture transcript':'AI topic guide · not a verified lecture summary'}</div><p className="guide-intro">{guide.summary}</p>{guide.keyIdeas?.map((k,i)=><article className="key-idea" key={i}><span>{i+1}</span><div><h3>{k.title}</h3><p>{k.explanation}</p></div></article>)}{guide.terms?.length>0&&<><h2 className="section-heading">Words worth knowing</h2><dl className="terms">{guide.terms.map((t,i)=><div key={i}><dt>{t.term}</dt><dd>{t.definition}</dd></div>)}</dl></>}<p className="fineprint">{guide.sourceNote||'AI-generated study material. Check contested claims against the source.'}</p><button className="button outline" onClick={()=>setTab('mastery')}>Check your understanding <ArrowRight size={18}/></button></>:guideTools)}
 {tab==='mastery'&&(guide?<><div className="tab-heading"><Lightbulb className="gold-text"/><div><h2>Can you explain it?</h2><p>Try answering aloud before revealing the guide.</p></div></div>{guide.mastery?.map((q,i)=><details className="mastery-question" key={i}><summary><span>{i+1}</span>{q.question}<ChevronDown size={19}/></summary><p>{q.answer}</p></details>)}<button className="button primary" onClick={()=>setTab('quiz')}>Take the quiz <Target size={18}/></button></>:guideTools)}
 {tab==='reflect'&&<><div className="tab-heading"><Heart className="coral"/><div><h2>Bring it into your life.</h2><p>Space for faith, uncertainty, and a good conversation.</p></div></div>{(guide?.reflection||['What challenged an assumption you brought to this lecture? What evidence might change your mind?','Where do you see a connection between this material and following Jesus today?','What would you and your study partner interpret differently, and why?']).map((q,i)=><div className="reflection-prompt" key={i}><span>{i+1}</span><p>{q}</p></div>)}<label className="note-label" htmlFor="reflection">{profile}’s reflection <small>Saved on this device</small></label><textarea id="reflection" className="reflection-input" placeholder="An insight, a question, a connection…" value={note} onChange={e=>setNote(e.target.value)} onBlur={()=>saveNote(l.id,note)}/><p className="fineprint">Your notes are not sent to the AI. Export a backup in Settings to move them to another device.</p></>}
 {tab==='quiz'&&(guide?.quiz?.length?quizActive?<Quiz questions={guide.quiz} onFinish={(correct,total,missed)=>recordQuiz(l.id,correct,total,missed)} close={()=>setQuizActive(false)} next={()=>setTab('reflect')}/>:<div className="quiz-start"><div className="quiz-symbol"><Target size={58}/></div><h2>Ready to put it together?</h2><p>{guide.quiz.length} questions · Explanations after every answer<br/>No timer. No lost hearts. Learn at your pace.</p>{person.quiz[l.id]&&<p className="best-score">Personal best: {Math.round(person.quiz[l.id].best/person.quiz[l.id].total*100)}%</p>}<button className="button primary" onClick={()=>setQuizActive(true)}>Start quiz <ArrowRight size={20}/></button><small>{guide.basis==='transcript'?'Questions based on the lecture transcript':'Supplementary topic quiz; not an instructor assessment'}</small></div>:guideTools)}
 {tab==='read'&&<><div className="tab-heading"><BookOpen className="teal"/><div><h2>Go to the sources.</h2><p>Assigned texts and supplementary reading are labeled separately.</p></div></div>{allReadings.length?allReadings.map((r,i)=><a className="reading-card" href={ext(r.url)} target="_blank" rel="noreferrer" key={i}><div><small>{r.kind||'Supplementary reading'}</small><h3>{r.title}</h3><p>{r.access||'Open at source'}</p></div><ExternalLink size={22}/></a>):<div className="empty-state"><BookOpen size={35}/><h3>No verified assigned reading found.</h3><p>The original course page is the authority for assignments. Supplementary suggestions may appear in the study guide.</p><a className="button outline" href={ext(c.url)} target="_blank" rel="noreferrer">View course materials <ExternalLink size={17}/></a></div>}</>}
 {tab==='transcript'&&<><div className="tab-heading"><ScrollText className="teal"/><div><h2>Follow the words.</h2><p>{source?.transcript?'Published course transcript':'Transcript availability depends on the provider.'}</p></div></div>{source?.transcript?<><label className="search-box"><Search size={20}/><input placeholder="Find a word or phrase" value={transcriptSearch} onChange={e=>setTranscriptSearch(e.target.value)}/></label><div className="transcript">{source.transcript.split('\n').filter(t=>t.trim()&&(!transcriptSearch||t.toLowerCase().includes(transcriptSearch.toLowerCase()))).map((t,i)=><p key={i}>{t}</p>)}</div><p className="fineprint">{source.attribution} <a href={ext(source.sourceUrl)} target="_blank" rel="noreferrer">Original transcript ↗</a></p></>:<div className="empty-state"><p>A full transcript has not been verified for this lecture. For YouTube lectures, open the video’s description and choose “Show transcript” if available.</p><a className="button outline" href={ext(l.url)} target="_blank" rel="noreferrer">Open transcript source <ExternalLink size={17}/></a><button className="text-button" onClick={()=>{setTab('summary');setShowPaste(true)}}>Add a transcript to study from</button>{source?.transcriptUrl&&<a href={source.transcriptUrl} target="_blank" rel="noreferrer">Read the provider’s transcript ↗</a>}</div>}</>}
 </div><footer className="lecture-footer"><button className={'button '+(person.done[l.id]?'outline':'primary')} onClick={()=>mark(l,!person.done[l.id])}><CheckCircle2 size={20}/>{person.done[l.id]?'Completed':'Mark complete'}</button>{next&&<a className="button outline" href={'#/lesson/'+next.id}>Next lesson <ArrowRight size={18}/></a>}</footer></>;
}
function Quiz({questions,onFinish,close,next}){const[index,setIndex]=useState(0),[choice,setChoice]=useState(null),[checked,setChecked]=useState(false),[answers,setAnswers]=useState([]),[finished,setFinished]=useState(false);const q=questions[index];const correct=answers.filter(Boolean).length;
 function advance(){const a=[...answers,choice===q.answer];setAnswers(a);if(index===questions.length-1){setFinished(true);onFinish(a.filter(Boolean).length,questions.length,a.map((v,i)=>v?null:i).filter(v=>v!==null))}else{setIndex(index+1);setChoice(null);setChecked(false)}}
 if(finished)return <div className="quiz-result"><img src="/lamb.webp" alt="A happy scholarly lamb"/><p className="eyebrow">PRACTICE COMPLETE</p><h2>{correct===questions.length?'Beautifully understood.':correct/questions.length>=.75?'Your understanding is growing.':'Every question is a new beginning.'}</h2><div className="result-stats"><div><strong>{Math.round(correct/questions.length*100)}%</strong><span>ACCURACY</span></div><div><strong>{correct}/{questions.length}</strong><span>CORRECT</span></div></div><p>{correct===questions.length?'Take a moment to connect these ideas with your life.':'Review the explanations below, then try again whenever you’re ready.'}</p><div className="result-actions"><button className="button primary" onClick={next}>Reflect together <Heart size={18}/></button><button className="button outline" onClick={close}>Back to quiz</button></div>{questions.map((q,i)=><details key={i} className="mastery-question"><summary>{answers[i]?<CheckCircle2 className="teal" size={20}/>:<RotateCcw className="coral" size={20}/>} {q.question}<ChevronDown size={18}/></summary><p><strong>{q.options[q.answer]}</strong><br/>{q.explanation}</p></details>)}</div>;
 return <div className="quiz"><div className="quiz-progress"><button className="plain" aria-label="Exit quiz" onClick={close}><X/></button><div className="track"><i style={{width:index/questions.length*100+'%'}}/></div><span>{index+1}/{questions.length}</span></div><p className="eyebrow">CHOOSE THE BEST ANSWER</p><h2>{q.question}</h2><div className="answers">{q.options.map((o,i)=><button className={'answer '+(choice===i?'chosen ':'')+(checked&&i===q.answer?'correct ':'')+(checked&&choice===i&&i!==q.answer?'incorrect':'')} disabled={checked} key={i} onClick={()=>setChoice(i)}><span>{String.fromCharCode(65+i)}</span>{o}{checked&&i===q.answer&&<Check size={20}/>}</button>)}</div>{checked&&<div className={'answer-feedback '+(choice===q.answer?'good':'try')} role="status"><h3>{choice===q.answer?'That’s right!':'A useful distinction.'}</h3><p>{q.explanation}</p></div>}<div className="quiz-bottom"><button className="button primary" disabled={choice===null} onClick={()=>checked?advance():setChecked(true)}>{checked?index===questions.length-1?'See results':'Continue':'Check answer'}<ArrowRight size={19}/></button></div></div>;
}
function SettingsModal({state,setState,close,notify}){const[msg,setMsg]=useState('');function backup(){const u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='bibledegree-progress-'+day()+'.json';a.click();URL.revokeObjectURL(u);notify('Progress backup downloaded')}
 async function restore(e){try{const f=e.target.files[0];if(!f)return;if(f.size>5000000)throw Error('Backup is too large.');const n=JSON.parse(await f.text());if(n.version!==1||!n.people?.Dalmo||!n.people?.Viv||!['Dalmo','Viv'].includes(n.active))throw Error('This is not a Bible Degree backup.');for(const p of Object.values(n.people))for(const k of ['done','quiz','notes','days'])if(!p[k]||typeof p[k]!=='object'||Array.isArray(p[k]))throw Error('The backup is incomplete.');setState(n);setMsg('Backup restored. Both learners are ready.')}catch(e){setMsg(e.message)}}
 return <div className="modal-overlay" onClick={e=>{if(e.target===e.currentTarget)close()}}><section className="modal" role="dialog" aria-modal="true" aria-label="Settings and backup"><button className="modal-close plain" onClick={close} aria-label="Close settings"><X/></button><Settings className="teal" size={30}/><h2>Make room for learning.</h2><label className="setting-row">Weekly lesson goal<select value={state.goal} onChange={e=>setState({...state,goal:Number(e.target.value)})}>{[1,2,3,5,7].map(n=><option key={n} value={n}>{n} lessons</option>)}</select></label><h3>Keep your progress safe</h3><p>Progress and reflections are saved in this browser. Export a backup before changing devices or clearing browser data. Importing replaces this device’s progress.</p><div className="backup-actions"><button className="button primary" onClick={backup}><Download size={18}/> Export backup</button><label className="button outline"><Upload size={18}/> Import backup<input type="file" accept="application/json,.json" onChange={restore} hidden/></label></div>{msg&&<p role="status">{msg}</p>}<hr/><small>Course videos remain with their original providers. AI study aids are supplementary. This is an independent learning companion, not an accredited degree program.</small></section></div>
}
createRoot(document.getElementById('root')).render(<App/>);
