import React,{useState,useEffect} from 'react';
import{createRoot}from'react-dom/client';
import{BookOpen,Map,Library,Gem,Target,Check,Play,ArrowRight,ArrowLeft,ChevronRight,ChevronDown,Trophy,Heart,Search,Clock,ExternalLink,CheckCircle2,Lightbulb,GraduationCap,ScrollText,Sparkles,X,RotateCcw,GitBranch,Monitor,Layers,Volume2}from'lucide-react';
import{STORAGE_KEY,readProgress,courseComplete,courseCount,scoreQuiz}from'./progress';
import{paths,adjacentCourses}from'./paths';
import './style.css';
const icons={learn:Map,courses:Library,practice:Target,progress:Trophy,roadmap:GitBranch};
const labels={learn:'Learn',courses:'Courses',practice:'Practice',progress:'Journey',roadmap:'Roadmap'};
const sections=['Biblical Studies','Theology & History','Philosophy, Ethics, etc.','Electives'];
function ext(url){return /^https?:\/\//.test(url||'')?url:'#'}
function App(){
 const[catalog,setCatalog]=useState([]),[state,setState]=useState(()=>readProgress(localStorage)),[route,setRoute]=useState(location.hash.slice(1)||'/learn'),[error,setError]=useState(''),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[showAll,setShowAll]=useState(false),[view,setView]=useState('paths');
 useEffect(()=>{fetch('/data/catalog.json').then(r=>{if(!r.ok)throw Error('Cannot load courses');return r.json()}).then(setCatalog).catch(e=>setError(e.message))},[]);
 useEffect(()=>{const h=()=>{setRoute(location.hash.slice(1)||'/learn');window.scrollTo(0,0)};window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h)},[]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{setError('This browser could not save progress. Check its storage settings.')}},[state]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t)}},[toast]);
 const lessonId=route.startsWith('/lesson/')?route.split('/')[2].split('?')[0]:null;
 const lessonCourse=lessonId?catalog.find(c=>c.lessons.some(l=>l.id===lessonId)):null;
 const lesson=lessonCourse?.lessons.find(l=>l.id===lessonId);
 useEffect(()=>{if(lessonCourse)setState(s=>s.selected===lessonCourse.id?s:{...s,selected:lessonCourse.id})},[lessonCourse?.id]);
 const course=lessonCourse||catalog.find(c=>c.id===state.selected)||catalog.find(c=>c.id==='c31');
 const completed=c=>courseComplete(c,state),count=c=>courseCount(c,state);
 const totalDone=catalog.filter(completed).length;
 const studied=catalog.reduce((sum,c)=>sum+count(c),0);
 const xp=Object.keys(state.done).filter(k=>!k.startsWith('course:')).length*20+Object.values(state.quiz).reduce((a,q)=>a+(q.best||0)*5,0);
 function update(fn){setState(s=>{const n=structuredClone(s);fn(n);return n})}
 function selectCourse(c){update(n=>n.selected=c.id);setShowAll(false);location.hash='/learn'}
 function mark(l,done=true){update(p=>{if(done)p.done[l.id]=new Date().toISOString();else delete p.done[l.id]});setToast(done?'Lesson complete. Keep growing!':'Lesson marked incomplete')}
 function recordQuiz(id,correct,total,mistakes){update(p=>p.quiz[id]=scoreQuiz(p.quiz[id],correct,total,mistakes))}
 const next=course?.lessons.find(l=>!state.done[l.id])||course?.lessons[0];
 const connections=course?adjacentCourses(course.id):{before:[],after:[]};
 const visible=catalog.filter(c=>(filter==='All'||c.section===filter)&&`${c.title} ${c.professor} ${c.area}`.toLowerCase().includes(search.toLowerCase()));
 const learning=route==='/learn'||route==='/'||route==='/notebook';
 if(error&&!catalog.length)return <div className="loading"><BookOpen size={50}/><h1>Let’s reconnect.</h1><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></div>;
 if(!course)return <div className="loading"><BookOpen className="breathe" size={52}/><h2>Opening your books…</h2></div>;
 const card=(c,i)=><button key={c.id} className="course-card" onClick={()=>selectCourse(c)}><div className={'course-emblem tone-'+i%4}>{completed(c)?<Check size={31}/>:<BookOpen size={31}/>}</div><div><small>{c.area}</small><h3>{c.title}</h3><p>{c.professor}</p><span>{c.lessons.length?`${c.lessons.length} lessons · `:''}{c.hours} hours{completed(c)?' · Completed':''}</span></div><ChevronRight size={22}/></button>;
 return <><aside className="sidebar"><a href="#/learn" className="brand"><BookOpen size={35} strokeWidth={3}/><span>bible<span>degree</span></span></a><nav>{Object.entries(labels).map(([k,v])=>{const Icon=icons[k];return <a key={k} href={'#/'+k} className={route==='/'+k?'active':''}><Icon/><span>{v}</span></a>})}</nav><div className="sidebar-bottom"><div className="local-mark"><Monitor size={21}/><span>Progress stays here.<br/><small>Saved in this browser.</small></span></div></div></aside>
 <div className="shell"><header className="topbar"><a href="#/learn" className="mobile-brand"><BookOpen/> bibledegree</a><span className="top-context">YOUR FREE THEOLOGICAL EDUCATION</span><div className="top-stats"><span title="Practice experience" className="xp"><Gem fill="#c4eef3" size={23}/>{xp}<small>XP</small></span><span className="local-indicator"><CheckCircle2 size={19}/> Saved locally</span></div></header>
 <div className={'body-grid '+(lesson?'lecture-grid':'')}><main id="main">
 {learning&&<><div className="page-heading"><div><p className="eyebrow">ONE STEP AT A TIME</p><h1>Your learning path</h1></div><button className="text-button" onClick={()=>location.hash='/courses'}>Change course <ChevronDown size={18}/></button></div><section className="course-banner"><div><span>{course.section.toUpperCase()}</span><h2>{course.title}</h2><p>{course.professor}</p></div><div className="banner-icon"><ScrollText size={48} strokeWidth={1.7}/></div><div className="banner-progress"><div className="track"><i style={{width:100*count(course)/(course.lessons.length||1)+'%'}}/></div><small>{count(course)} / {course.lessons.length} lessons</small></div></section>
 {course.note&&<p className="source-note">{course.note}</p>}
 <div className="path-intro"><span>{completed(course)?'READY FOR A REFRESH?':'YOUR NEXT LESSON'}</span><p>{next?.title||'Open the course to begin'}</p></div>
 {course.lessons.length?<div className="learning-path">{course.lessons.slice(0,showAll?undefined:8).map((l,i)=>{const done=completed(course)||state.done[l.id],active=l.id===next?.id;return <React.Fragment key={l.id}>{i>0&&i%6===0&&<div className="unit-divider"><span>CHAPTER {Math.floor(i/6)+1}</span><strong>Keep the story going</strong></div>}<div className={'path-stop '+(active?'current':'')+' '+(done?'finished':'')} style={{'--offset':`${[0,64,98,64,0,-64,-98,-64][i%8]}px`}}>{active&&<span className="start-callout">{done?'REVISIT':'START HERE'}</span>}<a className="lesson-node" href={'#/lesson/'+l.id} aria-label={'Lesson '+(i+1)+': '+l.title}>{done?<Check size={34} strokeWidth={4}/>:active?<Play size={31} fill="currentColor"/>:<BookOpen size={29}/>}</a><div className="path-label"><span>LESSON {i+1}{l.duration?' · '+l.duration:''}</span><strong>{l.title}</strong></div>{i===2&&<img src="/lamb.webp" className="path-lamb" alt="A cheerful lamb reading a book"/>}</div></React.Fragment>})}</div>:<div className="empty-state"><Library size={42}/><h2>Continue at the course provider</h2><p>{course.sourceIssue||'A verified lecture list is still being prepared.'}</p><a className="button primary" href={ext(course.url)} target="_blank" rel="noreferrer">Open course <ExternalLink size={18}/></a></div>}
 {!showAll&&course.lessons.length>8&&<button className="button outline more-lessons" onClick={()=>setShowAll(true)}>Show all {course.lessons.length} lessons <ChevronDown size={18}/></button>}
 <div className="course-footer"><a href={ext(course.url)} target="_blank" rel="noreferrer">Original course <ExternalLink size={15}/></a><button className="text-button" onClick={()=>{update(p=>{if(p.done['course:'+course.id])delete p.done['course:'+course.id];else p.done['course:'+course.id]=new Date().toISOString()});setToast('Course progress updated')}}>{state.done['course:'+course.id]?'Undo course completion':'Mark course completed'}</button></div>
 <CourseConnections connections={connections} catalog={catalog} selectCourse={selectCourse}/></>}
 {route==='/courses'&&<><div className="page-heading"><div><p className="eyebrow">BUILD ON WHAT YOU KNOW</p><h1>Your course library</h1><p>{catalog.length} courses · {catalog.reduce((s,c)=>s+c.hours,0).toLocaleString()} cataloged hours</p></div></div><div className="library-views"><button className={view==='paths'?'selected':''} onClick={()=>{setView('paths');setSearch('')}}><GitBranch size={19}/> Study paths</button><button className={view==='catalog'?'selected':''} onClick={()=>setView('catalog')}><Library size={19}/> All courses</button></div><label className="search-box"><Search size={22}/><input placeholder="Find a course, professor, or subject" value={search} onChange={e=>{setSearch(e.target.value);if(e.target.value)setView('catalog')}}/></label><div className="filter-row">{['All',...sections].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='Philosophy, Ethics, etc.'?'Philosophy & ethics':f}</button>)}</div>
 {view==='paths'?<><p className="pathway-intro">Suggested sequences. Follow the arrows; choose the courses that fit your aims. These are study recommendations, not formal prerequisites.</p>{paths.filter(p=>filter==='All'||p.section===filter).map(path=><section className="pathway" key={path.id}><h2><GitBranch size={22}/>{path.title}</h2><div className="course-tree">{path.stages.map((stage,i)=><React.Fragment key={stage.title}>{i>0&&<div className="tree-arrow" aria-label="then"><ArrowRight size={24}/></div>}<div className="tree-stage"><div className="tree-stage-title"><span>{i+1}</span>{stage.title}</div><div className="tree-branches">{stage.ids.map(id=>{const c=catalog.find(c=>c.id===id);return c&&<button className={'tree-course '+(completed(c)?'done':'')} key={id} onClick={()=>selectCourse(c)}><span>{completed(c)?<CheckCircle2 size={18}/>:<BookOpen size={18}/>}</span><strong>{c.title}</strong><small>{c.professor}</small><em>{c.lessons.length?`${c.lessons.length} lessons`:'View source & access details'}</em></button>})}</div></div></React.Fragment>)}</div></section>)}<h2 className="section-heading">Explore the full category</h2><div className="course-list">{visible.map(card)}</div></>:<div className="course-list">{visible.map(card)}</div>}
 {!visible.length&&<p className="empty-state">No courses match. Try another title or professor.</p>}<p className="fineprint">Hours are lecture estimates, not academic credits. Several courses cover similar ground. This independent curriculum does not award an accredited degree.</p></>}
 {lesson&&<Lesson key={lesson.id} lesson={lesson} course={lessonCourse} person={state} mark={mark} recordQuiz={recordQuiz}/>}
 {lessonId&&!lesson&&<div className="empty-state"><h1>Lesson not found</h1><a className="button primary" href="#/courses">Browse courses</a></div>}
 {route==='/practice'&&<><div className="page-heading"><div><p className="eyebrow">MAKE IT STICK</p><h1>Practice with purpose</h1></div></div><div className="practice-hero"><Target size={65}/><div><h2>Understanding grows with practice.</h2><p>Revisit the questions that deserve another look.</p></div></div><h2 className="section-heading">Your review queue</h2>{Object.entries(state.quiz).length?Object.entries(state.quiz).map(([id,q])=>{const c=catalog.find(c=>c.lessons.some(l=>l.id===id)),l=c?.lessons.find(l=>l.id===id);return l&&<a className="review-card" key={id} href={'#/lesson/'+id+'?tab=quiz'}><div><h3>{l.title}</h3><p>{q.mistakes?.length?`${q.mistakes.length} questions to revisit`:'Ready for a fresh review'} · {q.attempts} attempts</p></div><strong>{Math.round(q.best/q.total*100)}%</strong><ChevronRight/></a>}):<div className="empty-state"><Lightbulb size={42}/><h3>Start with a prepared lesson.</h3><p>Completed quizzes will appear here for review.</p><a className="button primary" href="#/lesson/c9-l1?tab=quiz">Practice an introductory lesson <ArrowRight size={18}/></a></div>}</>}
 {route==='/roadmap'&&<><div className="page-heading"><div><p className="eyebrow">WHAT COMES NEXT</p><h1>A deeper education</h1></div></div><section className="panel"><h2>Complete the lesson library</h2><p>72 full transcripts · 17 publisher transcript links · 4 complete study packs.</p><p>Of 1,938 lessons, 1,934 still need transcript-grounded summaries, mastery questions, reflections, and quizzes. Missing material is marked clearly in each lesson.</p></section><section className="panel"><h2>Build toward MDiv-level study</h2><p>Audit graduate learning outcomes, source advanced courses and readings, and add research assignments, language assessments, and a capstone. Expand preaching, pastoral care, worship, ethics, global Christianity, mission, and leadership.</p><p>Supervised ministry and formation require real communities and human guidance. This independent program does not award an accredited degree.</p></section><section className="panel"><h2>Later: accounts and conversations</h2><p>Optional Google sign-in and synced progress. A course-aware, lesson-aware chatbot alongside the published study materials.</p><a href="https://github.com/DalmoMendonca/bibledegree/blob/main/ROADMAP.md" target="_blank" rel="noreferrer">Read the detailed roadmap <ExternalLink size={16}/></a></section></>}
 {route==='/progress'&&<><div className="page-heading"><div><p className="eyebrow">LOOK HOW FAR YOU’VE COME</p><h1>Your journey</h1></div></div><div className="journey-hero"><img src="/lamb.webp" alt="Reading lamb"/><div><h2>{totalDone} courses completed</h2><p>{studied} lessons explored · {Object.keys(state.quiz).length} quizzes practiced</p><span className="gold-text">{xp} XP earned through practice</span></div></div><p className="source-note">Progress is saved automatically in this browser.</p><h2 className="section-heading">Your foundations</h2>{catalog.filter(completed).length?catalog.filter(completed).map(c=><div className="achievement" key={c.id}><div><GraduationCap size={33}/></div><span><h3>{c.title}</h3><p>{c.professor}</p><small>Course completed</small></span><CheckCircle2/></div>):<p className="muted">Your completed courses will gather here.</p>}<h2 className="section-heading">Across the curriculum</h2>{sections.map(s=>{const list=catalog.filter(c=>c.section===s),n=list.filter(completed).length;return <div className="subject-progress" key={s}><div><strong>{s}</strong><span>{n} / {list.length}</span></div><div className="track"><i style={{width:100*n/list.length+'%'}}/></div></div>})}</>}
 </main>{!lesson&&<aside className="right-rail"><section className="panel"><div className="panel-heading"><h3>Your next chapter</h3><Layers className="teal"/></div><p className="rail-progress"><strong>{studied}</strong> lessons completed</p><p className="muted">{totalDone} courses · {Object.keys(state.quiz).length} quizzes</p><a href="#/progress" className="text-button">See your journey <ArrowRight size={16}/></a></section><section className="panel"><div className="panel-heading"><h3>Connect the courses</h3><GitBranch className="teal" size={22}/></div><p className="muted">Survey → languages → exegesis → deeper study.</p><button className="text-button" onClick={()=>{setView('paths');location.hash='/courses'}}>Explore study paths <ArrowRight size={16}/></button></section><section className="encouragement"><img src="/lamb.webp" alt="Your scholarly lamb companion"/><div><h3>A little curiosity.<br/>A little every day.</h3><p>There’s a whole world<br/>behind the next lesson.</p></div></section><footer className="rail-footer"><span>Independent study · No tuition</span><span>Saved locally · No account needed</span></footer></aside>}</div></div>
 <nav className="mobile-nav" aria-label="Main navigation">{Object.entries(labels).map(([k,v])=>{const Icon=icons[k];return <a href={'#/'+k} key={k} className={route==='/'+k?'active':''}><Icon/><span>{v}</span></a>})}</nav>
 {toast&&<div role="status" className="toast"><CheckCircle2 size={20}/>{toast}</div>}{error&&<div role="alert" className="toast error">{error}</div>}
 </>;
}
function CourseConnections({connections,catalog,selectCourse}){return <section className="connections">{[['before','Build your foundation'],['after','Where this can lead']].map(([key,title])=>connections[key].length>0&&<div key={key}><h3>{title}</h3><div>{connections[key].map(id=>{const c=catalog.find(c=>c.id===id);return c&&<button className="connection-course" key={id} onClick={()=>selectCourse(c)}><BookOpen size={17}/><span>{c.title}</span><ArrowRight size={17}/></button>})}</div></div>)}{(connections.before.length>0||connections.after.length>0)&&<p className="fineprint">Suggested study sequence; courses remain open in any order.</p>}</section>}
function Lesson({lesson:l,course:c,person,mark,recordQuiz}){
 const initial=location.hash.split('?tab=')[1]||'watch';const[tab,setTab]=useState(initial),[source,setSource]=useState(null),[guide,setGuide]=useState(null),[loaded,setLoaded]=useState(false),[transcriptSearch,setTranscriptSearch]=useState(''),[quizActive,setQuizActive]=useState(false);
 const i=c.lessons.findIndex(x=>x.id===l.id),next=c.lessons[i+1];
 useEffect(()=>{let live=true;const read=async url=>{try{const r=await fetch(url);return r.ok&&r.headers.get('content-type')?.includes('json')?await r.json():null}catch{return null}};Promise.all([read('/data/lectures/'+l.id+'.json'),read('/data/guides/'+l.id+'.json')]).then(([s,g])=>{if(live){setSource(s);setGuide(g?.basis==='transcript'?g:null);setLoaded(true)}});return()=>{live=false}},[l.id]);
 const allReadings=[...(source?.readings||l.readings||[]),...(c.readings||[]),...(guide?.readings||[])];
 const guideTools=<div className="empty-state"><BookOpen size={36}/><h3>{loaded?'Study materials are being prepared.':'Opening the study materials…'}</h3>{loaded&&<><p>This lesson’s transcript-grounded summary, questions, and quiz are not published yet.</p><a className="button outline" href={ext(source?.sourceUrl||l.url||c.url)} target="_blank" rel="noreferrer">Open the lesson source <ExternalLink size={17}/></a></>}</div>;
 return <><a className="back-link" href="#/learn"><ArrowLeft size={19}/> Back to your path</a><div className="lecture-heading"><p className="eyebrow">{c.title} · LESSON {i+1} OF {c.lessons.length}</p><h1>{l.title}</h1><p>{c.professor}{l.duration&&<> <span>·</span> {l.duration}</>}</p></div><div className="lesson-tabs" role="tablist">{[['watch',Play,'Watch'],['summary',Sparkles,'Summary'],['mastery',Lightbulb,'Mastery'],['reflect',Heart,'Reflect'],['quiz',Target,'Quiz'],['read',BookOpen,'Readings'],['transcript',ScrollText,'Transcript']].map(([k,Icon,label])=><button key={k} role="tab" aria-selected={tab===k} className={tab===k?'selected':''} onClick={()=>{setTab(k);setQuizActive(false)}}><Icon size={18}/>{label}</button>)}</div>
 <div className="lesson-content" role="tabpanel">
 {tab==='watch'&&<><div className="video-wrap">{l.videoId?<iframe title={l.title} src={'https://www.youtube-nocookie.com/embed/'+l.videoId} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>:<div className="audio-placeholder"><Volume2 size={54}/><h2>Listen with the course provider</h2><p>This lecture is hosted as audio or on an external player.</p><a className="button primary" href={ext(l.url||c.url)} target="_blank" rel="noreferrer">Open lecture <ExternalLink size={18}/></a></div>}</div><div className="under-video"><span><Clock size={17}/>{l.duration||'Study at your own pace'}</span><a href={ext(l.url)} target="_blank" rel="noreferrer">{l.sourceKind==='course'?'Course provider':'Original lecture'} <ExternalLink size={16}/></a></div>{(source?.overview||l.overview)&&<section className="lecture-overview"><h2>In this lecture</h2><p>{source?.overview||l.overview}</p><small>Course provider’s overview · <a href={ext(l.url)} target="_blank" rel="noreferrer">Source</a></small></section>}<div className="next-action"><div><h3>Watch. Wonder. Make it yours.</h3><p>Then test your understanding and reflect together.</p></div><button className="button primary" onClick={()=>setTab('summary')}>Study this lesson <ArrowRight size={18}/></button></div></>}
 {tab==='summary'&&(guide?<><div className="ai-label"><Sparkles size={17}/>{guide.basis==='transcript'?'Lecture summary':'Study guide'}</div><p className="guide-intro">{guide.summary}</p>{guide.keyIdeas?.map((k,i)=><article className="key-idea" key={i}><span>{i+1}</span><div><h3>{k.title}</h3><p>{k.explanation}</p></div></article>)}{guide.terms?.length>0&&<><h2 className="section-heading">Words worth knowing</h2><dl className="terms">{guide.terms.map((t,i)=><div key={i}><dt>{t.term}</dt><dd>{t.definition}</dd></div>)}</dl></>}<p className="fineprint">{guide.sourceNote||'Prepared from the published lecture transcript.'}</p><button className="button outline" onClick={()=>setTab('mastery')}>Check your understanding <ArrowRight size={18}/></button></>:guideTools)}
 {tab==='mastery'&&(guide?<><div className="tab-heading"><Lightbulb className="gold-text"/><div><h2>Can you explain it?</h2><p>Try answering aloud before revealing the guide.</p></div></div>{guide.mastery?.map((q,i)=><details className="mastery-question" key={i}><summary><span>{i+1}</span>{q.question}<ChevronDown size={19}/></summary><p>{q.answer}</p></details>)}<button className="button primary" onClick={()=>setTab('quiz')}>Take the quiz <Target size={18}/></button></>:guideTools)}
 {tab==='reflect'&&(guide?.reflection?.length?<><div className="tab-heading"><Heart className="coral"/><div><h2>Think it through.</h2><p>Questions grounded in this lecture.</p></div></div>{guide.reflection.map((q,i)=><div className="reflection-prompt" key={i}><span>{i+1}</span><p>{q}</p></div>)}</>:guideTools)}
 {tab==='quiz'&&(guide?.quiz?.length?quizActive?<Quiz questions={guide.quiz} onFinish={(correct,total,missed)=>recordQuiz(l.id,correct,total,missed)} close={()=>setQuizActive(false)} next={()=>setTab('reflect')}/>:<div className="quiz-start"><div className="quiz-symbol"><Target size={58}/></div><h2>Ready to put it together?</h2><p>{guide.quiz.length} questions · Explanations after every answer<br/>No timer. No lost hearts. Learn at your pace.</p>{person.quiz[l.id]&&<p className="best-score">Personal best: {Math.round(person.quiz[l.id].best/person.quiz[l.id].total*100)}%</p>}<button className="button primary" onClick={()=>setQuizActive(true)}>Start quiz <ArrowRight size={20}/></button><small>{guide.basis==='transcript'?'Questions based on the lecture transcript':'Supplementary topic quiz; not an instructor assessment'}</small></div>:guideTools)}
 {tab==='read'&&<><div className="tab-heading"><BookOpen className="teal"/><div><h2>Go to the sources.</h2><p>Assigned texts and supplementary reading are labeled separately.</p></div></div>{allReadings.length?allReadings.map((r,i)=><a className="reading-card" href={ext(r.url)} target="_blank" rel="noreferrer" key={i}><div><small>{r.kind||'Supplementary reading'}</small><h3>{r.title}</h3><p>{r.access||'Open at source'}</p></div><ExternalLink size={22}/></a>):<div className="empty-state"><BookOpen size={35}/><h3>No verified assigned reading found.</h3><p>The original course page is the authority for assignments. </p><a className="button outline" href={ext(c.url)} target="_blank" rel="noreferrer">View course materials <ExternalLink size={17}/></a></div>}</>}
 {tab==='transcript'&&<><div className="tab-heading"><ScrollText className="teal"/><div><h2>Follow the words.</h2><p>{source?.transcript?'Published course transcript':'Transcript availability depends on the provider.'}</p></div></div>{source?.transcript?<><label className="search-box"><Search size={20}/><input placeholder="Find a word or phrase" value={transcriptSearch} onChange={e=>setTranscriptSearch(e.target.value)}/></label><div className="transcript">{source.transcript.split('\n').filter(t=>t.trim()&&(!transcriptSearch||t.toLowerCase().includes(transcriptSearch.toLowerCase()))).map((t,i)=><p key={i}>{t}</p>)}</div><p className="fineprint">{source.attribution} <a href={ext(source.sourceUrl)} target="_blank" rel="noreferrer">Original transcript ↗</a></p></>:<div className="empty-state"><p>A full transcript has not been verified for this lecture. For YouTube lectures, open the video’s description and choose “Show transcript” if available.</p><a className="button outline" href={ext(l.url)} target="_blank" rel="noreferrer">Open transcript source <ExternalLink size={17}/></a>{source?.transcriptUrl&&<a href={source.transcriptUrl} target="_blank" rel="noreferrer">Read the provider’s transcript ↗</a>}</div>}</>}
 </div><footer className="lecture-footer"><button className={'button '+(person.done[l.id]?'outline':'primary')} onClick={()=>mark(l,!person.done[l.id])}><CheckCircle2 size={20}/>{person.done[l.id]?'Completed':'Mark complete'}</button>{next&&<a className="button outline" href={'#/lesson/'+next.id}>Next lesson <ArrowRight size={18}/></a>}</footer></>;
}
function Quiz({questions,onFinish,close,next}){const[index,setIndex]=useState(0),[choice,setChoice]=useState(null),[checked,setChecked]=useState(false),[answers,setAnswers]=useState([]),[finished,setFinished]=useState(false);const q=questions[index];const correct=answers.filter(Boolean).length;
 function advance(){const a=[...answers,choice===q.answer];setAnswers(a);if(index===questions.length-1){setFinished(true);onFinish(a.filter(Boolean).length,questions.length,a.map((v,i)=>v?null:i).filter(v=>v!==null))}else{setIndex(index+1);setChoice(null);setChecked(false)}}
 if(finished)return <div className="quiz-result"><img src="/lamb.webp" alt="A happy scholarly lamb"/><p className="eyebrow">PRACTICE COMPLETE</p><h2>{correct===questions.length?'Beautifully understood.':correct/questions.length>=.75?'Your understanding is growing.':'Every question is a new beginning.'}</h2><div className="result-stats"><div><strong>{Math.round(correct/questions.length*100)}%</strong><span>ACCURACY</span></div><div><strong>{correct}/{questions.length}</strong><span>CORRECT</span></div></div><p>{correct===questions.length?'Take a moment to connect these ideas with your life.':'Review the explanations below, then try again whenever you’re ready.'}</p><div className="result-actions"><button className="button primary" onClick={next}>Reflect on the lesson <Heart size={18}/></button><button className="button outline" onClick={close}>Back to quiz</button></div>{questions.map((q,i)=><details key={i} className="mastery-question"><summary>{answers[i]?<CheckCircle2 className="teal" size={20}/>:<RotateCcw className="coral" size={20}/>} {q.question}<ChevronDown size={18}/></summary><p><strong>{q.options[q.answer]}</strong><br/>{q.explanation}</p></details>)}</div>;
 return <div className="quiz"><div className="quiz-progress"><button className="plain" aria-label="Exit quiz" onClick={close}><X/></button><div className="track"><i style={{width:index/questions.length*100+'%'}}/></div><span>{index+1}/{questions.length}</span></div><p className="eyebrow">CHOOSE THE BEST ANSWER</p><h2>{q.question}</h2><div className="answers">{q.options.map((o,i)=><button className={'answer '+(choice===i?'chosen ':'')+(checked&&i===q.answer?'correct ':'')+(checked&&choice===i&&i!==q.answer?'incorrect':'')} disabled={checked} key={i} onClick={()=>setChoice(i)}><span>{String.fromCharCode(65+i)}</span>{o}{checked&&i===q.answer&&<Check size={20}/>}</button>)}</div>{checked&&<div className={'answer-feedback '+(choice===q.answer?'good':'try')} role="status"><h3>{choice===q.answer?'That’s right!':'A useful distinction.'}</h3><p>{q.explanation}</p></div>}<div className="quiz-bottom"><button className="button primary" disabled={choice===null} onClick={()=>checked?advance():setChecked(true)}>{checked?index===questions.length-1?'See results':'Continue':'Check answer'}<ArrowRight size={19}/></button></div></div>;
}

createRoot(document.getElementById('root')).render(<App/>);
